#15 usersテーブルにnameカラムを追加してputのテスト
YosukeSasaoka/tba-app-api pull request #19
Opened 2016-12-06 17:27 UTC by NRintaro

アクセスURL
localhost:3000/api/v1/users/me/name?token=トークン

params
{
  "name": "HelloWorld"
}

putのテストのため、usersテーブルにnameカラムを追加してます。
今後putの処理を書く参考にするために実装しました。

2016-12-25 03:51 UTC, MitsuhiroKamei requested changes
nameの変更がDBに反映されませんでした。

2016-12-25 03:51 UTC, MitsuhiroKamei commented on app/models/user.rb
> +    return if self.name = new_name
if self.name == new_name
ではないでしょうか?

2016-12-25 03:54 UTC, rockymanobi commented on app/models/user.rb
> +  def update_user_name!(new_name)
すげ〜〜〜細かいことをいうと、呼び出し側からすれば`user.update_user_name( "hoge" )`ってなるのでメソッド名は`update_name!`で良い気がするよ。

2016-12-25 04:36 UTC, MitsuhiroKamei commented on app/apis/api/v1/user_api.rb
> +          # joinsしてるからreadonly(false)で治る
こちらについて、
app/models/api_key.rb
のコードの方に、コメントをさせて頂きました。
ご確認いただければと思います。

2017-01-11 09:23 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

これ自分で対応します。終わったら連絡します。

2017-01-15 07:14 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

修正しておきましたので確認をお願いします。

2017-01-15 08:14 UTC, MitsuhiroKamei commented
@yosuke.sasaoka
修正ありがとうございます。しかしながら、動作確認してみましたが、
まだ、ユーザー名の更新には失敗してしまいます。
DHCでテストしたときのレスポンスのBODYを添付します。
(ダウンロードしたら拡張子をhtmlに変更して開いてください)

さらに修正が必要な個所があるのではないでしょうか?
例えば、以前こちらの方で、コメントさせて頂いていたのですが、

https://github.com/YosukeSasaoka/tba-app-api/commit/32083e9f4f56f560569e1e0ba794203709b75b9a

app/models/api_key.rb の authenticate() は、修正の必要は無いのでしょうか

[error.txt](https://github.com/YosukeSasaoka/tba-app-api/files/706470/error.txt)

2017-01-15 08:45 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

すみません、DHCでテストを行っている時の画面のキャプチャーを貼ってもらえないでしょうか？

2017-01-15 08:54 UTC, MitsuhiroKamei commented
@yosuke.sasaoka

承知しました。
キャプチャした画像を添付します。
![error](https://cloud.githubusercontent.com/assets/9022059/21961373/a1fe6432-db4b-11e6-812f-5001df0c7110.png)

ユーザー名(name)は
DB内の"kamei" を "kamei7"に変更しようとしています。

2017-01-15 08:55 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

ありがとうございます。
確認します。

2017-01-15 10:57 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

修正しましたので確認をお願いします。

2017-01-15 11:04 UTC, MitsuhiroKamei commented
@yosuke.sasaoka

修正を適用し、動作を確認しました。
ありがとうございました。

2017-01-31 14:19 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

すみませんmergeします。

2017-01-31 14:19 UTC, merged